[build]
  command = "yarn build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 